[package]
name = "clionRustTest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
tui = "0.18"
crossterm = "0.23"
image = "0.24.2"
ndarray = "0.15.4"